fontSize = 25;

x = linspace(0,200,200);
y1 = sin(2*pi*x/40);
y2 = sin(2*pi*x/(1/2200*48000));
y = cat(2, y1(1:40), y2(1:40), y1(34:73), y2(20:59),y1(30:69));
y = y + 0.7*sin(pi*x/200);
f = figure('Position',[0,0,1280,1024]);
set(gcf,'color','w');
plot(x, y);
filename = 'Effects of a DC Offset on a Signal';
title(filename);
xlabel('Sample Number');
ylabel('Magnitude');
minY = min(y);
maxY = max(y);
center = (minY+maxY)/ 2;
rangeY = maxY - minY;
adjustedRange = 0.55*rangeY;
minY = (center - adjustedRange);
maxY = (center + adjustedRange);
ylim([minY maxY]);
set(gca,'FontSize',fontSize,'fontWeight','bold');
set(findall(gcf,'type','text'),'FontSize',fontSize,'fontWeight','bold');
yL = get(gca,'YLim');
xL = get(gca,'XLim');
line([40 40],yL,'Color','r');
line([80 80],yL,'Color','r');
line([120 120],yL,'Color','r');
line([160 160],yL,'Color','r');
line(xL,[0 0],'Color','black');
saveas(f, strcat('.\..\..\..\rrxthesis\images\',regexprep(filename,'[^\w'']',''),'.png'));
pause();
close(f);
clear all;