fontSize = 25;

x = linspace(0,100,1000);
y = sin(x);
f = figure('Position',[0,0,1280,1024]);
set(gcf,'color','w');
plot(x, y);
filename = 'General Sine Curve';
title(filename);
xlabel('Radians');
ylabel('Magnitude');
minY = min(y);
maxY = max(y);
center = (minY+maxY)/ 2;
rangeY = maxY - minY;
adjustedRange = 0.55*rangeY;
minY = (center - adjustedRange);
maxY = (center + adjustedRange);
ylim([minY maxY]);
set(gca,'FontSize',fontSize,'fontWeight','bold');
set(findall(gcf,'type','text'),'FontSize',fontSize,'fontWeight','bold');
saveas(f, strcat('.\..\..\rrxthesis\images\',regexprep(filename,'[^\w'']',''),'.png'));
pause();
close(f);