fontSize = 18;

x = linspace(0,100,1000);
y = sin(x);
f = figure('Position',[0,0,1280,1024]);
set(gcf,'color','w');
plot(x, y);
filename = 'General Sine Curve';
title(filename);
xlabel('Radians');
ylabel('Magnitude');
minY = min(y);
maxY = max(y);
center = (minY+maxY)/ 2;
rangeY = maxY - minY;
adjustedRange = 0.55*rangeY;
minY = (center - adjustedRange);
maxY = (center + adjustedRange);
ylim([minY maxY]);
set(gca,'FontSize',fontSize,'fontWeight','bold');
set(findall(gcf,'type','text'),'FontSize',fontSize,'fontWeight','bold');
display('The error must be after here...');
filename =  strcat('./../../rrxthesis/images/',regexprep(filename,'[^\w'']',''),'.png');
display(strcat('Trying to sage as ', filename));
saveas(f,filename);
%pause();
close(f);
